# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'THREDDS_Explorer_mix_dockwidget_base.ui'
#
# Created: Mon Feb 20 18:42:53 2017
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_THREDDSViewer(object):
    def setupUi(self, THREDDSViewer):
        THREDDSViewer.setObjectName(_fromUtf8("THREDDSViewer"))
        THREDDSViewer.resize(593, 964)
        THREDDSViewer.setMinimumSize(QtCore.QSize(98, 118))
        THREDDSViewer.setFloating(True)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_7 = QtGui.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 573, 919))
        self.scrollAreaWidgetContents_7.setObjectName(_fromUtf8("scrollAreaWidgetContents_7"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents_7)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.combo_dataset_list = QtGui.QComboBox(self.scrollAreaWidgetContents_7)
        self.combo_dataset_list.setObjectName(_fromUtf8("combo_dataset_list"))
        self.gridLayout.addWidget(self.combo_dataset_list, 6, 0, 1, 1)
        self.label_dataset = QtGui.QLabel(self.scrollAreaWidgetContents_7)
        self.label_dataset.setObjectName(_fromUtf8("label_dataset"))
        self.gridLayout.addWidget(self.label_dataset, 5, 0, 1, 1)
        self.label_product = QtGui.QLabel(self.scrollAreaWidgetContents_7)
        self.label_product.setObjectName(_fromUtf8("label_product"))
        self.gridLayout.addWidget(self.label_product, 3, 0, 1, 1)
        self.combo_product_list = QtGui.QComboBox(self.scrollAreaWidgetContents_7)
        self.combo_product_list.setObjectName(_fromUtf8("combo_product_list"))
        self.gridLayout.addWidget(self.combo_product_list, 4, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.combo_area_list = QtGui.QComboBox(self.scrollAreaWidgetContents_7)
        self.combo_area_list.setObjectName(_fromUtf8("combo_area_list"))
        self.gridLayout.addWidget(self.combo_area_list, 2, 0, 1, 1)
        self.label_area = QtGui.QLabel(self.scrollAreaWidgetContents_7)
        self.label_area.setObjectName(_fromUtf8("label_area"))
        self.gridLayout.addWidget(self.label_area, 1, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_variable = QtGui.QLabel(self.scrollAreaWidgetContents_7)
        self.label_variable.setObjectName(_fromUtf8("label_variable"))
        self.verticalLayout.addWidget(self.label_variable)
        self.combo_variable_list = QtGui.QComboBox(self.scrollAreaWidgetContents_7)
        self.combo_variable_list.setObjectName(_fromUtf8("combo_variable_list"))
        self.verticalLayout.addWidget(self.combo_variable_list)
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents_7)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 300))
        self.tabWidget.setMaximumSize(QtCore.QSize(10000, 500))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_WMS = QtGui.QWidget()
        self.tab_WMS.setObjectName(_fromUtf8("tab_WMS"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_WMS)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tab_WMS_layout = QtGui.QVBoxLayout()
        self.tab_WMS_layout.setObjectName(_fromUtf8("tab_WMS_layout"))
        self.label_depth = QtGui.QLabel(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_depth.sizePolicy().hasHeightForWidth())
        self.label_depth.setSizePolicy(sizePolicy)
        self.label_depth.setObjectName(_fromUtf8("label_depth"))
        self.tab_WMS_layout.addWidget(self.label_depth)
        self.combo_wms_layer_depth = QtGui.QComboBox(self.tab_WMS)
        self.combo_wms_layer_depth.setObjectName(_fromUtf8("combo_wms_layer_depth"))
        self.tab_WMS_layout.addWidget(self.combo_wms_layer_depth)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.combo_proj = QtGui.QComboBox(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_proj.sizePolicy().hasHeightForWidth())
        self.combo_proj.setSizePolicy(sizePolicy)
        self.combo_proj.setObjectName(_fromUtf8("combo_proj"))
        self.gridLayout_5.addWidget(self.combo_proj, 1, 1, 1, 1)
        self.label_style = QtGui.QLabel(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_style.sizePolicy().hasHeightForWidth())
        self.label_style.setSizePolicy(sizePolicy)
        self.label_style.setObjectName(_fromUtf8("label_style"))
        self.gridLayout_5.addWidget(self.label_style, 0, 0, 1, 1)
        self.combo_colorbar = QtGui.QComboBox(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_colorbar.sizePolicy().hasHeightForWidth())
        self.combo_colorbar.setSizePolicy(sizePolicy)
        self.combo_colorbar.setObjectName(_fromUtf8("combo_colorbar"))
        self.gridLayout_5.addWidget(self.combo_colorbar, 1, 0, 1, 1)
        self.tab_WMS_layout.addLayout(self.gridLayout_5)
        self.WMSLabelTimeRange = QtGui.QLabel(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WMSLabelTimeRange.sizePolicy().hasHeightForWidth())
        self.WMSLabelTimeRange.setSizePolicy(sizePolicy)
        self.WMSLabelTimeRange.setObjectName(_fromUtf8("WMSLabelTimeRange"))
        self.tab_WMS_layout.addWidget(self.WMSLabelTimeRange)
        self.layout_time = QtGui.QGridLayout()
        self.layout_time.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.layout_time.setSpacing(6)
        self.layout_time.setObjectName(_fromUtf8("layout_time"))
        self.combo_wms_time_last_d = QtGui.QComboBox(self.tab_WMS)
        self.combo_wms_time_last_d.setObjectName(_fromUtf8("combo_wms_time_last_d"))
        self.layout_time.addWidget(self.combo_wms_time_last_d, 1, 0, 1, 1)
        self.combo_wms_time_last_h = QtGui.QComboBox(self.tab_WMS)
        self.combo_wms_time_last_h.setObjectName(_fromUtf8("combo_wms_time_last_h"))
        self.layout_time.addWidget(self.combo_wms_time_last_h, 1, 1, 1, 1)
        self.combo_wms_time_first_d = QtGui.QComboBox(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_wms_time_first_d.sizePolicy().hasHeightForWidth())
        self.combo_wms_time_first_d.setSizePolicy(sizePolicy)
        self.combo_wms_time_first_d.setObjectName(_fromUtf8("combo_wms_time_first_d"))
        self.layout_time.addWidget(self.combo_wms_time_first_d, 0, 0, 1, 1)
        self.combo_wms_time_first_h = QtGui.QComboBox(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_wms_time_first_h.sizePolicy().hasHeightForWidth())
        self.combo_wms_time_first_h.setSizePolicy(sizePolicy)
        self.combo_wms_time_first_h.setObjectName(_fromUtf8("combo_wms_time_first_h"))
        self.layout_time.addWidget(self.combo_wms_time_first_h, 0, 1, 1, 1)
        self.tab_WMS_layout.addLayout(self.layout_time)
        self.label = QtGui.QLabel(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.tab_WMS_layout.addWidget(self.label)
        self.WMS_Bounds = QtGui.QGridLayout()
        self.WMS_Bounds.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.WMS_Bounds.setObjectName(_fromUtf8("WMS_Bounds"))
        self.WMS_westBound = QtGui.QLineEdit(self.tab_WMS)
        self.WMS_westBound.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WMS_westBound.sizePolicy().hasHeightForWidth())
        self.WMS_westBound.setSizePolicy(sizePolicy)
        self.WMS_westBound.setMinimumSize(QtCore.QSize(171, 9))
        self.WMS_westBound.setObjectName(_fromUtf8("WMS_westBound"))
        self.WMS_Bounds.addWidget(self.WMS_westBound, 1, 0, 1, 1)
        self.WMS_northBound = QtGui.QLineEdit(self.tab_WMS)
        self.WMS_northBound.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WMS_northBound.sizePolicy().hasHeightForWidth())
        self.WMS_northBound.setSizePolicy(sizePolicy)
        self.WMS_northBound.setObjectName(_fromUtf8("WMS_northBound"))
        self.WMS_Bounds.addWidget(self.WMS_northBound, 0, 1, 1, 1)
        self.WMS_southBound = QtGui.QLineEdit(self.tab_WMS)
        self.WMS_southBound.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WMS_southBound.sizePolicy().hasHeightForWidth())
        self.WMS_southBound.setSizePolicy(sizePolicy)
        self.WMS_southBound.setObjectName(_fromUtf8("WMS_southBound"))
        self.WMS_Bounds.addWidget(self.WMS_southBound, 2, 1, 1, 1)
        self.WMS_northLabel = QtGui.QLabel(self.tab_WMS)
        self.WMS_northLabel.setText(_fromUtf8(""))
        self.WMS_northLabel.setObjectName(_fromUtf8("WMS_northLabel"))
        self.WMS_Bounds.addWidget(self.WMS_northLabel, 1, 1, 1, 1)
        self.WMS_eastBound = QtGui.QLineEdit(self.tab_WMS)
        self.WMS_eastBound.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WMS_eastBound.sizePolicy().hasHeightForWidth())
        self.WMS_eastBound.setSizePolicy(sizePolicy)
        self.WMS_eastBound.setObjectName(_fromUtf8("WMS_eastBound"))
        self.WMS_Bounds.addWidget(self.WMS_eastBound, 1, 2, 1, 1)
        self.tab_WMS_layout.addLayout(self.WMS_Bounds)
        self.gridLayout_4.addLayout(self.tab_WMS_layout, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_WMS)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_WMS, _fromUtf8(""))
        self.tab_WCS = QtGui.QWidget()
        self.tab_WCS.setObjectName(_fromUtf8("tab_WCS"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_WCS)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tab_WCS_layout = QtGui.QVBoxLayout()
        self.tab_WCS_layout.setObjectName(_fromUtf8("tab_WCS_layout"))
        self.combo_wcs_coverage = QtGui.QComboBox(self.tab_WCS)
        self.combo_wcs_coverage.setObjectName(_fromUtf8("combo_wcs_coverage"))
        self.tab_WCS_layout.addWidget(self.combo_wcs_coverage)
        self.WCSLabelTimeRange = QtGui.QLabel(self.tab_WCS)
        self.WCSLabelTimeRange.setMaximumSize(QtCore.QSize(16777215, 25))
        self.WCSLabelTimeRange.setObjectName(_fromUtf8("WCSLabelTimeRange"))
        self.tab_WCS_layout.addWidget(self.WCSLabelTimeRange)
        self.combo_wcs_time = QtGui.QComboBox(self.tab_WCS)
        self.combo_wcs_time.setObjectName(_fromUtf8("combo_wcs_time"))
        self.tab_WCS_layout.addWidget(self.combo_wcs_time)
        self.combo_wcs_time_last = QtGui.QComboBox(self.tab_WCS)
        self.combo_wcs_time_last.setObjectName(_fromUtf8("combo_wcs_time_last"))
        self.tab_WCS_layout.addWidget(self.combo_wcs_time_last)
        self.WCSBoundingBoxInfo = QtGui.QLabel(self.tab_WCS)
        self.WCSBoundingBoxInfo.setObjectName(_fromUtf8("WCSBoundingBoxInfo"))
        self.tab_WCS_layout.addWidget(self.WCSBoundingBoxInfo)
        self.WCS_Bounds = QtGui.QGridLayout()
        self.WCS_Bounds.setObjectName(_fromUtf8("WCS_Bounds"))
        self.WCS_southBound = QtGui.QLineEdit(self.tab_WCS)
        self.WCS_southBound.setObjectName(_fromUtf8("WCS_southBound"))
        self.WCS_Bounds.addWidget(self.WCS_southBound, 2, 1, 1, 1)
        self.WCS_northBound = QtGui.QLineEdit(self.tab_WCS)
        self.WCS_northBound.setObjectName(_fromUtf8("WCS_northBound"))
        self.WCS_Bounds.addWidget(self.WCS_northBound, 0, 1, 1, 1)
        self.WCS_westBound = QtGui.QLineEdit(self.tab_WCS)
        self.WCS_westBound.setObjectName(_fromUtf8("WCS_westBound"))
        self.WCS_Bounds.addWidget(self.WCS_westBound, 1, 0, 1, 1)
        self.WCS_eastBound = QtGui.QLineEdit(self.tab_WCS)
        self.WCS_eastBound.setObjectName(_fromUtf8("WCS_eastBound"))
        self.WCS_Bounds.addWidget(self.WCS_eastBound, 1, 2, 1, 1)
        self.tab_WCS_layout.addLayout(self.WCS_Bounds)
        self.gridLayout_6.addLayout(self.tab_WCS_layout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_WCS, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_3.addWidget(self.lineEdit, 10, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 9, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 9, 0, 1, 1)
        self.button = QtGui.QLineEdit(self.scrollAreaWidgetContents_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button.sizePolicy().hasHeightForWidth())
        self.button.setSizePolicy(sizePolicy)
        self.button.setObjectName(_fromUtf8("button"))
        self.gridLayout_3.addWidget(self.button, 10, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents_7)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 9, 3, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.scrollAreaWidgetContents_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_3.addWidget(self.lineEdit_3, 10, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 11, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.scrollAreaWidgetContents_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 11, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.scrollAreaWidgetContents_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 11, 3, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.scrollAreaWidgetContents_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_3.addWidget(self.lineEdit_2, 12, 0, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.scrollAreaWidgetContents_7)
        self.lineEdit_4.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(16777215, 16777197))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout_3.addWidget(self.lineEdit_4, 12, 1, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.scrollAreaWidgetContents_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout_3.addWidget(self.lineEdit_5, 12, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.button_req_map = QtGui.QPushButton(self.scrollAreaWidgetContents_7)
        self.button_req_map.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_req_map.sizePolicy().hasHeightForWidth())
        self.button_req_map.setSizePolicy(sizePolicy)
        self.button_req_map.setMaximumSize(QtCore.QSize(256, 32))
        self.button_req_map.setObjectName(_fromUtf8("button_req_map"))
        self.verticalLayout.addWidget(self.button_req_map)
        self.button_req_animation = QtGui.QPushButton(self.scrollAreaWidgetContents_7)
        self.button_req_animation.setObjectName(_fromUtf8("button_req_animation"))
        self.verticalLayout.addWidget(self.button_req_animation)
        self.gridLayout.addLayout(self.verticalLayout, 8, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_7)
        self.verticalLayout_2.addWidget(self.scrollArea)
        THREDDSViewer.setWidget(self.dockWidgetContents)

        self.retranslateUi(THREDDSViewer)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(THREDDSViewer)

    def retranslateUi(self, THREDDSViewer):
        THREDDSViewer.setWindowTitle(_translate("THREDDSViewer", "THREDDS Explorer", None))
        self.label_dataset.setText(_translate("THREDDSViewer", "Choose Dataset:", None))
        self.label_product.setText(_translate("THREDDSViewer", "Choose Product:", None))
        self.label_area.setText(_translate("THREDDSViewer", "Choose Area:", None))
        self.label_variable.setText(_translate("THREDDSViewer", "Choose Variable:", None))
        self.label_depth.setText(_translate("THREDDSViewer", "Choose Depth:", None))
        self.label_style.setText(_translate("THREDDSViewer", "Choose Style :", None))
        self.WMSLabelTimeRange.setText(_translate("THREDDSViewer", "Time range to download:", None))
        self.combo_wms_time_first_h.setToolTip(_translate("THREDDSViewer", "Last time value to download for this layer\n"
"(If set, will download all the layers between the first and last times)", None))
        self.label.setText(_translate("THREDDSViewer", "Bounding Box:", None))
        self.label_2.setText(_translate("THREDDSViewer", "Plot parameters :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_WMS), _translate("THREDDSViewer", "WMS", None))
        self.WCSLabelTimeRange.setText(_translate("THREDDSViewer", "Time range to download:", None))
        self.combo_wcs_time.setToolTip(_translate("THREDDSViewer", "First time value to download for this layer", None))
        self.combo_wcs_time_last.setToolTip(_translate("THREDDSViewer", "Last time value to download for this layer\n"
"(If set, will download all the layers between the first and last times)", None))
        self.WCSBoundingBoxInfo.setText(_translate("THREDDSViewer", "No bounding box info available", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_WCS), _translate("THREDDSViewer", "WCS", None))
        self.label_4.setText(_translate("THREDDSViewer", "Max scale", None))
        self.label_3.setText(_translate("THREDDSViewer", "Min scale", None))
        self.label_5.setText(_translate("THREDDSViewer", "Nb colors", None))
        self.label_6.setText(_translate("THREDDSViewer", "XParallels", None))
        self.label_7.setText(_translate("THREDDSViewer", "YMedians", None))
        self.label_8.setText(_translate("THREDDSViewer", "Xpixels", None))
        self.button_req_map.setText(_translate("THREDDSViewer", "Show map in view", None))
        self.button_req_animation.setText(_translate("THREDDSViewer", "Show animation menu >>", None))

