# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cmems_dialogbox_wms.ui'
#
# Created: Wed Feb  1 17:27:04 2017
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(579, 881)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(230, 820, 341, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(60, 20, 491, 71))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.comboBox = QtGui.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(220, 20, 241, 31))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(0, 20, 101, 31))
        self.label.setObjectName(_fromUtf8("label"))
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(50, 90, 491, 71))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.comboBox_2 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_2.setGeometry(QtCore.QRect(140, 20, 331, 31))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(0, 20, 111, 31))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(50, 160, 491, 71))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.comboBox_3 = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_3.setGeometry(QtCore.QRect(140, 20, 331, 31))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(0, 20, 111, 31))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(50, 230, 491, 71))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.comboBox_4 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_4.setGeometry(QtCore.QRect(140, 20, 331, 31))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(0, 20, 121, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.groupBox_5 = QtGui.QGroupBox(Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(40, 300, 521, 161))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_5 = QtGui.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(0, 60, 101, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit.setGeometry(QtCore.QRect(125, 59, 121, 41))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_2.setGeometry(QtCore.QRect(365, 55, 121, 41))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_3.setGeometry(QtCore.QRect(247, 19, 113, 41))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_4.setGeometry(QtCore.QRect(242, 100, 121, 41))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.label_6 = QtGui.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(165, 38, 71, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(395, 28, 66, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(275, 78, 66, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setGeometry(QtCore.QRect(270, -1, 66, 21))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.groupBox_6 = QtGui.QGroupBox(Dialog)
        self.groupBox_6.setGeometry(QtCore.QRect(50, 450, 491, 71))
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.comboBox_5 = QtGui.QComboBox(self.groupBox_6)
        self.comboBox_5.setGeometry(QtCore.QRect(110, 20, 181, 31))
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.label_10 = QtGui.QLabel(self.groupBox_6)
        self.label_10.setGeometry(QtCore.QRect(0, 20, 41, 31))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.comboBox_6 = QtGui.QComboBox(self.groupBox_6)
        self.comboBox_6.setGeometry(QtCore.QRect(310, 20, 171, 29))
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.groupBox_7 = QtGui.QGroupBox(Dialog)
        self.groupBox_7.setGeometry(QtCore.QRect(30, 510, 541, 71))
        self.groupBox_7.setTitle(_fromUtf8(""))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.comboBox_7 = QtGui.QComboBox(self.groupBox_7)
        self.comboBox_7.setGeometry(QtCore.QRect(130, 20, 281, 31))
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.label_11 = QtGui.QLabel(self.groupBox_7)
        self.label_11.setGeometry(QtCore.QRect(20, 20, 51, 31))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.groupBox_8 = QtGui.QGroupBox(Dialog)
        self.groupBox_8.setGeometry(QtCore.QRect(40, 580, 511, 141))
        self.groupBox_8.setTitle(_fromUtf8(""))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.comboBox_8 = QtGui.QComboBox(self.groupBox_8)
        self.comboBox_8.setGeometry(QtCore.QRect(90, 30, 141, 31))
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.label_12 = QtGui.QLabel(self.groupBox_8)
        self.label_12.setGeometry(QtCore.QRect(10, 30, 71, 31))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.lineEdit_5 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_5.setGeometry(QtCore.QRect(260, 30, 113, 33))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_6.setGeometry(QtCore.QRect(390, 30, 113, 33))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.lineEdit_7 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_7.setGeometry(QtCore.QRect(262, 100, 111, 33))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_8.setGeometry(QtCore.QRect(390, 100, 111, 33))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.label_13 = QtGui.QLabel(self.groupBox_8)
        self.label_13.setGeometry(QtCore.QRect(280, 0, 66, 21))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.groupBox_8)
        self.label_14.setGeometry(QtCore.QRect(410, 0, 66, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.groupBox_8)
        self.label_15.setGeometry(QtCore.QRect(280, 70, 66, 21))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.groupBox_8)
        self.label_16.setGeometry(QtCore.QRect(420, 70, 66, 21))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.comboBox_9 = QtGui.QComboBox(self.groupBox_8)
        self.comboBox_9.setGeometry(QtCore.QRect(110, 100, 111, 29))
        self.comboBox_9.setObjectName(_fromUtf8("comboBox_9"))
        self.label_17 = QtGui.QLabel(self.groupBox_8)
        self.label_17.setGeometry(QtCore.QRect(10, 100, 91, 31))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.groupBox_9 = QtGui.QGroupBox(Dialog)
        self.groupBox_9.setGeometry(QtCore.QRect(50, 710, 501, 91))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.lineEdit_9 = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_9.setGeometry(QtCore.QRect(150, 20, 81, 33))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.lineEdit_10 = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_10.setGeometry(QtCore.QRect(260, 20, 81, 33))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.lineEdit_11 = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_11.setGeometry(QtCore.QRect(370, 20, 61, 33))
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.label_20 = QtGui.QLabel(self.groupBox_9)
        self.label_20.setGeometry(QtCore.QRect(380, 0, 31, 21))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_18 = QtGui.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(210, 730, 66, 21))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(310, 730, 71, 21))
        self.label_19.setObjectName(_fromUtf8("label_19"))

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Choose Area </span></p></body></html>", None))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Choose Product</span></p></body></html>", None))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Choose Dataset</span></p></body></html>", None))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Choose Variable</span></p></body></html>", None))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Defined Area</span></p></body></html>", None))
        self.label_6.setText(_translate("Dialog", "Lon min", None))
        self.label_7.setText(_translate("Dialog", "Lon max", None))
        self.label_8.setText(_translate("Dialog", "Lat min", None))
        self.label_9.setText(_translate("Dialog", "Lat max", None))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Time</span></p></body></html>", None))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Depth</span></p></body></html>", None))
        self.label_12.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Colorbar</span></p></body></html>", None))
        self.label_13.setText(_translate("Dialog", "MinValue", None))
        self.label_14.setText(_translate("Dialog", "MaxValue", None))
        self.label_15.setText(_translate("Dialog", "Nb Colors", None))
        self.label_16.setText(_translate("Dialog", "Xpixels", None))
        self.label_17.setText(_translate("Dialog", "Input format", None))
        self.groupBox_9.setTitle(_translate("Dialog", "Plot definition", None))
        self.label_20.setText(_translate("Dialog", "Dpi", None))
        self.label_18.setText(_translate("Dialog", "Xparallels", None))
        self.label_19.setText(_translate("Dialog", "Ymeridians", None))

