# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'THREDDS_Explorer_extract_Multi_WMS_dockwidget_base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_THREDDSViewer(object):
    def setupUi(self, THREDDSViewer):
        THREDDSViewer.setObjectName(_fromUtf8("THREDDSViewer"))
        THREDDSViewer.resize(549, 936)
        THREDDSViewer.setMinimumSize(QtCore.QSize(161, 118))
        THREDDSViewer.setFloating(True)
        self.dockWidgetContents = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget_Multi_WMS = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget_Multi_WMS.setObjectName(_fromUtf8("tabWidget_Multi_WMS"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.layoutWidget_3 = QtGui.QWidget(self.tab)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 0, 521, 849))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout_7.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout_7.setVerticalSpacing(6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.combo_dataset_cmems_list = QtGui.QComboBox(self.layoutWidget_3)
        self.combo_dataset_cmems_list.setObjectName(_fromUtf8("combo_dataset_cmems_list"))
        self.gridLayout_7.addWidget(self.combo_dataset_cmems_list, 9, 0, 1, 1)
        self.combo_variable_list = QtGui.QComboBox(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_variable_list.sizePolicy().hasHeightForWidth())
        self.combo_variable_list.setSizePolicy(sizePolicy)
        self.combo_variable_list.setObjectName(_fromUtf8("combo_variable_list"))
        self.gridLayout_7.addWidget(self.combo_variable_list, 11, 0, 1, 1)
        self.label_dataset = QtGui.QLabel(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_dataset.sizePolicy().hasHeightForWidth())
        self.label_dataset.setSizePolicy(sizePolicy)
        self.label_dataset.setObjectName(_fromUtf8("label_dataset"))
        self.gridLayout_7.addWidget(self.label_dataset, 8, 0, 1, 1)
        self.combo_product_list = QtGui.QComboBox(self.layoutWidget_3)
        self.combo_product_list.setObjectName(_fromUtf8("combo_product_list"))
        self.gridLayout_7.addWidget(self.combo_product_list, 7, 0, 1, 1)
        self.label_variable = QtGui.QLabel(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_variable.sizePolicy().hasHeightForWidth())
        self.label_variable.setSizePolicy(sizePolicy)
        self.label_variable.setObjectName(_fromUtf8("label_variable"))
        self.gridLayout_7.addWidget(self.label_variable, 10, 0, 1, 1)
        self.combo_area_list = QtGui.QComboBox(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_area_list.sizePolicy().hasHeightForWidth())
        self.combo_area_list.setSizePolicy(sizePolicy)
        self.combo_area_list.setObjectName(_fromUtf8("combo_area_list"))
        self.gridLayout_7.addWidget(self.combo_area_list, 3, 0, 1, 1)
        self.label_area = QtGui.QLabel(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_area.sizePolicy().hasHeightForWidth())
        self.label_area.setSizePolicy(sizePolicy)
        self.label_area.setObjectName(_fromUtf8("label_area"))
        self.gridLayout_7.addWidget(self.label_area, 2, 0, 1, 1)
        self.label_product = QtGui.QLabel(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_product.sizePolicy().hasHeightForWidth())
        self.label_product.setSizePolicy(sizePolicy)
        self.label_product.setObjectName(_fromUtf8("label_product"))
        self.gridLayout_7.addWidget(self.label_product, 6, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.verticalLayout_4.setContentsMargins(-1, -1, 4, 6)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.ExtractWidget_2 = QtGui.QTabWidget(self.layoutWidget_3)
        self.ExtractWidget_2.setEnabled(True)
        self.ExtractWidget_2.setMaximumSize(QtCore.QSize(10000, 600))
        self.ExtractWidget_2.setObjectName(_fromUtf8("ExtractWidget_2"))
        self.tab_WMS_2 = QtGui.QWidget()
        self.tab_WMS_2.setObjectName(_fromUtf8("tab_WMS_2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_WMS_2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_4 = QtGui.QLabel(self.tab_WMS_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_8.addWidget(self.label_4, 3, 0, 1, 1)
        self.tab_WMS_layout_2 = QtGui.QVBoxLayout()
        self.tab_WMS_layout_2.setSpacing(0)
        self.tab_WMS_layout_2.setObjectName(_fromUtf8("tab_WMS_layout_2"))
        self.label_depth = QtGui.QLabel(self.tab_WMS_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_depth.sizePolicy().hasHeightForWidth())
        self.label_depth.setSizePolicy(sizePolicy)
        self.label_depth.setObjectName(_fromUtf8("label_depth"))
        self.tab_WMS_layout_2.addWidget(self.label_depth)
        self.combo_wms_layer_depth = QtGui.QComboBox(self.tab_WMS_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_wms_layer_depth.sizePolicy().hasHeightForWidth())
        self.combo_wms_layer_depth.setSizePolicy(sizePolicy)
        self.combo_wms_layer_depth.setObjectName(_fromUtf8("combo_wms_layer_depth"))
        self.tab_WMS_layout_2.addWidget(self.combo_wms_layer_depth)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setVerticalSpacing(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.combo_proj = QtGui.QComboBox(self.tab_WMS_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_proj.sizePolicy().hasHeightForWidth())
        self.combo_proj.setSizePolicy(sizePolicy)
        self.combo_proj.setObjectName(_fromUtf8("combo_proj"))
        self.gridLayout_9.addWidget(self.combo_proj, 1, 1, 1, 1)
        self.label_style = QtGui.QLabel(self.tab_WMS_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_style.sizePolicy().hasHeightForWidth())
        self.label_style.setSizePolicy(sizePolicy)
        self.label_style.setObjectName(_fromUtf8("label_style"))
        self.gridLayout_9.addWidget(self.label_style, 0, 0, 1, 1)
        self.combo_colorbar = QtGui.QComboBox(self.tab_WMS_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_colorbar.sizePolicy().hasHeightForWidth())
        self.combo_colorbar.setSizePolicy(sizePolicy)
        self.combo_colorbar.setObjectName(_fromUtf8("combo_colorbar"))
        self.gridLayout_9.addWidget(self.combo_colorbar, 1, 0, 1, 1)
        self.tab_WMS_layout_2.addLayout(self.gridLayout_9)
        self.WMSLabelTimeRange_2 = QtGui.QLabel(self.tab_WMS_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WMSLabelTimeRange_2.sizePolicy().hasHeightForWidth())
        self.WMSLabelTimeRange_2.setSizePolicy(sizePolicy)
        self.WMSLabelTimeRange_2.setMinimumSize(QtCore.QSize(300, 0))
        self.WMSLabelTimeRange_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.WMSLabelTimeRange_2.setIndent(-1)
        self.WMSLabelTimeRange_2.setObjectName(_fromUtf8("WMSLabelTimeRange_2"))
        self.tab_WMS_layout_2.addWidget(self.WMSLabelTimeRange_2)
        self.layout_time_3 = QtGui.QGridLayout()
        self.layout_time_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.layout_time_3.setHorizontalSpacing(6)
        self.layout_time_3.setVerticalSpacing(2)
        self.layout_time_3.setObjectName(_fromUtf8("layout_time_3"))
        self.combo_wms_time_last_d = QtGui.QComboBox(self.tab_WMS_2)
        self.combo_wms_time_last_d.setObjectName(_fromUtf8("combo_wms_time_last_d"))
        self.layout_time_3.addWidget(self.combo_wms_time_last_d, 1, 0, 1, 1)
        self.combo_wms_time_last_h = QtGui.QComboBox(self.tab_WMS_2)
        self.combo_wms_time_last_h.setObjectName(_fromUtf8("combo_wms_time_last_h"))
        self.layout_time_3.addWidget(self.combo_wms_time_last_h, 1, 1, 1, 1)
        self.combo_wms_time_first_d = QtGui.QComboBox(self.tab_WMS_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_wms_time_first_d.sizePolicy().hasHeightForWidth())
        self.combo_wms_time_first_d.setSizePolicy(sizePolicy)
        self.combo_wms_time_first_d.setObjectName(_fromUtf8("combo_wms_time_first_d"))
        self.layout_time_3.addWidget(self.combo_wms_time_first_d, 0, 0, 1, 1)
        self.combo_wms_time_first_h = QtGui.QComboBox(self.tab_WMS_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_wms_time_first_h.sizePolicy().hasHeightForWidth())
        self.combo_wms_time_first_h.setSizePolicy(sizePolicy)
        self.combo_wms_time_first_h.setObjectName(_fromUtf8("combo_wms_time_first_h"))
        self.layout_time_3.addWidget(self.combo_wms_time_first_h, 0, 1, 1, 1)
        self.tab_WMS_layout_2.addLayout(self.layout_time_3)
        self.label_2 = QtGui.QLabel(self.tab_WMS_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.tab_WMS_layout_2.addWidget(self.label_2)
        self.WMS_Bounds_3 = QtGui.QGridLayout()
        self.WMS_Bounds_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.WMS_Bounds_3.setHorizontalSpacing(5)
        self.WMS_Bounds_3.setVerticalSpacing(1)
        self.WMS_Bounds_3.setObjectName(_fromUtf8("WMS_Bounds_3"))
        self.lat_WMS_northBound = QtGui.QLineEdit(self.tab_WMS_2)
        self.lat_WMS_northBound.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lat_WMS_northBound.sizePolicy().hasHeightForWidth())
        self.lat_WMS_northBound.setSizePolicy(sizePolicy)
        self.lat_WMS_northBound.setObjectName(_fromUtf8("lat_WMS_northBound"))
        self.WMS_Bounds_3.addWidget(self.lat_WMS_northBound, 0, 1, 1, 1)
        self.lat_WMS_southBound = QtGui.QLineEdit(self.tab_WMS_2)
        self.lat_WMS_southBound.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lat_WMS_southBound.sizePolicy().hasHeightForWidth())
        self.lat_WMS_southBound.setSizePolicy(sizePolicy)
        self.lat_WMS_southBound.setObjectName(_fromUtf8("lat_WMS_southBound"))
        self.WMS_Bounds_3.addWidget(self.lat_WMS_southBound, 2, 1, 1, 1)
        self.WMS_northLabel_2 = QtGui.QLabel(self.tab_WMS_2)
        self.WMS_northLabel_2.setText(_fromUtf8(""))
        self.WMS_northLabel_2.setObjectName(_fromUtf8("WMS_northLabel_2"))
        self.WMS_Bounds_3.addWidget(self.WMS_northLabel_2, 1, 1, 1, 1)
        self.lon_WMS_eastBound = QtGui.QLineEdit(self.tab_WMS_2)
        self.lon_WMS_eastBound.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lon_WMS_eastBound.sizePolicy().hasHeightForWidth())
        self.lon_WMS_eastBound.setSizePolicy(sizePolicy)
        self.lon_WMS_eastBound.setObjectName(_fromUtf8("lon_WMS_eastBound"))
        self.WMS_Bounds_3.addWidget(self.lon_WMS_eastBound, 1, 2, 1, 1)
        self.lon_WMS_westBound = QtGui.QLineEdit(self.tab_WMS_2)
        self.lon_WMS_westBound.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lon_WMS_westBound.sizePolicy().hasHeightForWidth())
        self.lon_WMS_westBound.setSizePolicy(sizePolicy)
        self.lon_WMS_westBound.setMinimumSize(QtCore.QSize(171, 9))
        self.lon_WMS_westBound.setObjectName(_fromUtf8("lon_WMS_westBound"))
        self.WMS_Bounds_3.addWidget(self.lon_WMS_westBound, 1, 0, 1, 1)
        self.tab_WMS_layout_2.addLayout(self.WMS_Bounds_3)
        self.gridLayout_8.addLayout(self.tab_WMS_layout_2, 0, 0, 3, 1)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout_10.setHorizontalSpacing(6)
        self.gridLayout_10.setVerticalSpacing(0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_Xpixels = QtGui.QLabel(self.tab_WMS_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Xpixels.sizePolicy().hasHeightForWidth())
        self.label_Xpixels.setSizePolicy(sizePolicy)
        self.label_Xpixels.setObjectName(_fromUtf8("label_Xpixels"))
        self.gridLayout_10.addWidget(self.label_Xpixels, 11, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_nbcolors = QtGui.QLabel(self.tab_WMS_2)
        self.label_nbcolors.setObjectName(_fromUtf8("label_nbcolors"))
        self.gridLayout_10.addWidget(self.label_nbcolors, 9, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_maxscale = QtGui.QLabel(self.tab_WMS_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_maxscale.sizePolicy().hasHeightForWidth())
        self.label_maxscale.setSizePolicy(sizePolicy)
        self.label_maxscale.setObjectName(_fromUtf8("label_maxscale"))
        self.gridLayout_10.addWidget(self.label_maxscale, 9, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.Ymedians_value = QtGui.QLineEdit(self.tab_WMS_2)
        self.Ymedians_value.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ymedians_value.sizePolicy().hasHeightForWidth())
        self.Ymedians_value.setSizePolicy(sizePolicy)
        self.Ymedians_value.setMaximumSize(QtCore.QSize(16777215, 16777197))
        self.Ymedians_value.setObjectName(_fromUtf8("Ymedians_value"))
        self.gridLayout_10.addWidget(self.Ymedians_value, 12, 1, 1, 1)
        self.checkBox_arc = QtGui.QCheckBox(self.tab_WMS_2)
        self.checkBox_arc.setObjectName(_fromUtf8("checkBox_arc"))
        self.gridLayout_10.addWidget(self.checkBox_arc, 13, 0, 1, 1)
        self.Xparallels_value = QtGui.QLineEdit(self.tab_WMS_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Xparallels_value.sizePolicy().hasHeightForWidth())
        self.Xparallels_value.setSizePolicy(sizePolicy)
        self.Xparallels_value.setObjectName(_fromUtf8("Xparallels_value"))
        self.gridLayout_10.addWidget(self.Xparallels_value, 12, 0, 1, 1)
        self.minscale_value = QtGui.QLineEdit(self.tab_WMS_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minscale_value.sizePolicy().hasHeightForWidth())
        self.minscale_value.setSizePolicy(sizePolicy)
        self.minscale_value.setObjectName(_fromUtf8("minscale_value"))
        self.gridLayout_10.addWidget(self.minscale_value, 10, 0, 1, 1)
        self.maxscale_value = QtGui.QLineEdit(self.tab_WMS_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxscale_value.sizePolicy().hasHeightForWidth())
        self.maxscale_value.setSizePolicy(sizePolicy)
        self.maxscale_value.setObjectName(_fromUtf8("maxscale_value"))
        self.gridLayout_10.addWidget(self.maxscale_value, 10, 1, 1, 1)
        self.label_minscale = QtGui.QLabel(self.tab_WMS_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_minscale.sizePolicy().hasHeightForWidth())
        self.label_minscale.setSizePolicy(sizePolicy)
        self.label_minscale.setObjectName(_fromUtf8("label_minscale"))
        self.gridLayout_10.addWidget(self.label_minscale, 9, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_ant = QtGui.QCheckBox(self.tab_WMS_2)
        self.checkBox_ant.setObjectName(_fromUtf8("checkBox_ant"))
        self.gridLayout_10.addWidget(self.checkBox_ant, 13, 1, 1, 1)
        self.nbcolors_value = QtGui.QLineEdit(self.tab_WMS_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nbcolors_value.sizePolicy().hasHeightForWidth())
        self.nbcolors_value.setSizePolicy(sizePolicy)
        self.nbcolors_value.setObjectName(_fromUtf8("nbcolors_value"))
        self.gridLayout_10.addWidget(self.nbcolors_value, 10, 3, 1, 1)
        self.Xpixels_value = QtGui.QLineEdit(self.tab_WMS_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Xpixels_value.sizePolicy().hasHeightForWidth())
        self.Xpixels_value.setSizePolicy(sizePolicy)
        self.Xpixels_value.setObjectName(_fromUtf8("Xpixels_value"))
        self.gridLayout_10.addWidget(self.Xpixels_value, 12, 3, 1, 1)
        self.label_Ymedians = QtGui.QLabel(self.tab_WMS_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Ymedians.sizePolicy().hasHeightForWidth())
        self.label_Ymedians.setSizePolicy(sizePolicy)
        self.label_Ymedians.setObjectName(_fromUtf8("label_Ymedians"))
        self.gridLayout_10.addWidget(self.label_Ymedians, 11, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_Xparallels = QtGui.QLabel(self.tab_WMS_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Xparallels.sizePolicy().hasHeightForWidth())
        self.label_Xparallels.setSizePolicy(sizePolicy)
        self.label_Xparallels.setObjectName(_fromUtf8("label_Xparallels"))
        self.gridLayout_10.addWidget(self.label_Xparallels, 11, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_8.addLayout(self.gridLayout_10, 4, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_WMS_2)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.button_req_map_plot = QtGui.QPushButton(self.groupBox_2)
        self.button_req_map_plot.setEnabled(True)
        self.button_req_map_plot.setGeometry(QtCore.QRect(0, 10, 191, 35))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_req_map_plot.sizePolicy().hasHeightForWidth())
        self.button_req_map_plot.setSizePolicy(sizePolicy)
        self.button_req_map_plot.setMinimumSize(QtCore.QSize(0, 35))
        self.button_req_map_plot.setMaximumSize(QtCore.QSize(256, 30))
        self.button_req_map_plot.setObjectName(_fromUtf8("button_req_map_plot"))
        self.button_req_animation_plot = QtGui.QPushButton(self.groupBox_2)
        self.button_req_animation_plot.setGeometry(QtCore.QRect(300, 10, 171, 35))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_req_animation_plot.sizePolicy().hasHeightForWidth())
        self.button_req_animation_plot.setSizePolicy(sizePolicy)
        self.button_req_animation_plot.setMinimumSize(QtCore.QSize(20, 35))
        self.button_req_animation_plot.setMaximumSize(QtCore.QSize(250, 30))
        self.button_req_animation_plot.setIconSize(QtCore.QSize(24, 24))
        self.button_req_animation_plot.setObjectName(_fromUtf8("button_req_animation_plot"))
        self.gridLayout_8.addWidget(self.groupBox_2, 5, 0, 3, 1)
        self.ExtractWidget_2.addTab(self.tab_WMS_2, _fromUtf8(""))
        self.tab_WCS_2 = QtGui.QWidget()
        self.tab_WCS_2.setObjectName(_fromUtf8("tab_WCS_2"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tab_WCS_2)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.tab_WCS_layout_2 = QtGui.QVBoxLayout()
        self.tab_WCS_layout_2.setObjectName(_fromUtf8("tab_WCS_layout_2"))
        self.combo_wcs_coverage_2 = QtGui.QComboBox(self.tab_WCS_2)
        self.combo_wcs_coverage_2.setObjectName(_fromUtf8("combo_wcs_coverage_2"))
        self.tab_WCS_layout_2.addWidget(self.combo_wcs_coverage_2)
        self.WCSLabelTimeRange_2 = QtGui.QLabel(self.tab_WCS_2)
        self.WCSLabelTimeRange_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.WCSLabelTimeRange_2.setObjectName(_fromUtf8("WCSLabelTimeRange_2"))
        self.tab_WCS_layout_2.addWidget(self.WCSLabelTimeRange_2)
        self.combo_wcs_time_2 = QtGui.QComboBox(self.tab_WCS_2)
        self.combo_wcs_time_2.setObjectName(_fromUtf8("combo_wcs_time_2"))
        self.tab_WCS_layout_2.addWidget(self.combo_wcs_time_2)
        self.combo_wcs_time_last_2 = QtGui.QComboBox(self.tab_WCS_2)
        self.combo_wcs_time_last_2.setObjectName(_fromUtf8("combo_wcs_time_last_2"))
        self.tab_WCS_layout_2.addWidget(self.combo_wcs_time_last_2)
        self.WCSBoundingBoxInfo_2 = QtGui.QLabel(self.tab_WCS_2)
        self.WCSBoundingBoxInfo_2.setObjectName(_fromUtf8("WCSBoundingBoxInfo_2"))
        self.tab_WCS_layout_2.addWidget(self.WCSBoundingBoxInfo_2)
        self.WCS_Bounds_2 = QtGui.QGridLayout()
        self.WCS_Bounds_2.setObjectName(_fromUtf8("WCS_Bounds_2"))
        self.WCS_southBound_2 = QtGui.QLineEdit(self.tab_WCS_2)
        self.WCS_southBound_2.setObjectName(_fromUtf8("WCS_southBound_2"))
        self.WCS_Bounds_2.addWidget(self.WCS_southBound_2, 2, 1, 1, 1)
        self.WCS_northBound_2 = QtGui.QLineEdit(self.tab_WCS_2)
        self.WCS_northBound_2.setObjectName(_fromUtf8("WCS_northBound_2"))
        self.WCS_Bounds_2.addWidget(self.WCS_northBound_2, 0, 1, 1, 1)
        self.WCS_westBound_2 = QtGui.QLineEdit(self.tab_WCS_2)
        self.WCS_westBound_2.setObjectName(_fromUtf8("WCS_westBound_2"))
        self.WCS_Bounds_2.addWidget(self.WCS_westBound_2, 1, 0, 1, 1)
        self.WCS_eastBound_2 = QtGui.QLineEdit(self.tab_WCS_2)
        self.WCS_eastBound_2.setObjectName(_fromUtf8("WCS_eastBound_2"))
        self.WCS_Bounds_2.addWidget(self.WCS_eastBound_2, 1, 2, 1, 1)
        self.tab_WCS_layout_2.addLayout(self.WCS_Bounds_2)
        self.gridLayout_11.addLayout(self.tab_WCS_layout_2, 0, 0, 1, 1)
        self.ExtractWidget_2.addTab(self.tab_WCS_2, _fromUtf8(""))
        self.tab_WPS_2 = QtGui.QWidget()
        self.tab_WPS_2.setObjectName(_fromUtf8("tab_WPS_2"))
        self.ExtractWidget_2.addTab(self.tab_WPS_2, _fromUtf8(""))
        self.tab_Extract_2 = QtGui.QWidget()
        self.tab_Extract_2.setObjectName(_fromUtf8("tab_Extract_2"))
        self.label_depth_4 = QtGui.QLabel(self.tab_Extract_2)
        self.label_depth_4.setGeometry(QtCore.QRect(10, 20, 527, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_depth_4.sizePolicy().hasHeightForWidth())
        self.label_depth_4.setSizePolicy(sizePolicy)
        self.label_depth_4.setObjectName(_fromUtf8("label_depth_4"))
        self.combo_wms_layer_depth_2 = QtGui.QComboBox(self.tab_Extract_2)
        self.combo_wms_layer_depth_2.setGeometry(QtCore.QRect(10, 60, 201, 31))
        self.combo_wms_layer_depth_2.setObjectName(_fromUtf8("combo_wms_layer_depth_2"))
        self.WMSLabelTimeRange_4 = QtGui.QLabel(self.tab_Extract_2)
        self.WMSLabelTimeRange_4.setGeometry(QtCore.QRect(10, 100, 527, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WMSLabelTimeRange_4.sizePolicy().hasHeightForWidth())
        self.WMSLabelTimeRange_4.setSizePolicy(sizePolicy)
        self.WMSLabelTimeRange_4.setObjectName(_fromUtf8("WMSLabelTimeRange_4"))
        self.layoutWidget_4 = QtGui.QWidget(self.tab_Extract_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 140, 461, 71))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.layout_time_4 = QtGui.QGridLayout(self.layoutWidget_4)
        self.layout_time_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.layout_time_4.setSpacing(6)
        self.layout_time_4.setObjectName(_fromUtf8("layout_time_4"))
        self.combo_wms_time_last_d_2 = QtGui.QComboBox(self.layoutWidget_4)
        self.combo_wms_time_last_d_2.setObjectName(_fromUtf8("combo_wms_time_last_d_2"))
        self.layout_time_4.addWidget(self.combo_wms_time_last_d_2, 1, 0, 1, 1)
        self.combo_wms_time_last_h_2 = QtGui.QComboBox(self.layoutWidget_4)
        self.combo_wms_time_last_h_2.setObjectName(_fromUtf8("combo_wms_time_last_h_2"))
        self.layout_time_4.addWidget(self.combo_wms_time_last_h_2, 1, 1, 1, 1)
        self.combo_wms_time_first_d_2 = QtGui.QComboBox(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_wms_time_first_d_2.sizePolicy().hasHeightForWidth())
        self.combo_wms_time_first_d_2.setSizePolicy(sizePolicy)
        self.combo_wms_time_first_d_2.setObjectName(_fromUtf8("combo_wms_time_first_d_2"))
        self.layout_time_4.addWidget(self.combo_wms_time_first_d_2, 0, 0, 1, 1)
        self.combo_wms_time_first_h_2 = QtGui.QComboBox(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_wms_time_first_h_2.sizePolicy().hasHeightForWidth())
        self.combo_wms_time_first_h_2.setSizePolicy(sizePolicy)
        self.combo_wms_time_first_h_2.setObjectName(_fromUtf8("combo_wms_time_first_h_2"))
        self.layout_time_4.addWidget(self.combo_wms_time_first_h_2, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_Extract_2)
        self.label_10.setGeometry(QtCore.QRect(10, 220, 527, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.layoutWidget_5 = QtGui.QWidget(self.tab_Extract_2)
        self.layoutWidget_5.setGeometry(QtCore.QRect(16, 250, 451, 113))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.WMS_Bounds_4 = QtGui.QGridLayout(self.layoutWidget_5)
        self.WMS_Bounds_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.WMS_Bounds_4.setObjectName(_fromUtf8("WMS_Bounds_4"))
        self.lon_WMS_westBound_2 = QtGui.QLineEdit(self.layoutWidget_5)
        self.lon_WMS_westBound_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lon_WMS_westBound_2.sizePolicy().hasHeightForWidth())
        self.lon_WMS_westBound_2.setSizePolicy(sizePolicy)
        self.lon_WMS_westBound_2.setMinimumSize(QtCore.QSize(171, 9))
        self.lon_WMS_westBound_2.setObjectName(_fromUtf8("lon_WMS_westBound_2"))
        self.WMS_Bounds_4.addWidget(self.lon_WMS_westBound_2, 1, 0, 1, 1)
        self.lat_WMS_northBound_2 = QtGui.QLineEdit(self.layoutWidget_5)
        self.lat_WMS_northBound_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lat_WMS_northBound_2.sizePolicy().hasHeightForWidth())
        self.lat_WMS_northBound_2.setSizePolicy(sizePolicy)
        self.lat_WMS_northBound_2.setObjectName(_fromUtf8("lat_WMS_northBound_2"))
        self.WMS_Bounds_4.addWidget(self.lat_WMS_northBound_2, 0, 1, 1, 1)
        self.lat_WMS_southBound_2 = QtGui.QLineEdit(self.layoutWidget_5)
        self.lat_WMS_southBound_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lat_WMS_southBound_2.sizePolicy().hasHeightForWidth())
        self.lat_WMS_southBound_2.setSizePolicy(sizePolicy)
        self.lat_WMS_southBound_2.setObjectName(_fromUtf8("lat_WMS_southBound_2"))
        self.WMS_Bounds_4.addWidget(self.lat_WMS_southBound_2, 2, 1, 1, 1)
        self.WMS_northLabel_3 = QtGui.QLabel(self.layoutWidget_5)
        self.WMS_northLabel_3.setText(_fromUtf8(""))
        self.WMS_northLabel_3.setObjectName(_fromUtf8("WMS_northLabel_3"))
        self.WMS_Bounds_4.addWidget(self.WMS_northLabel_3, 1, 1, 1, 1)
        self.lon_WMS_eastBound_2 = QtGui.QLineEdit(self.layoutWidget_5)
        self.lon_WMS_eastBound_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lon_WMS_eastBound_2.sizePolicy().hasHeightForWidth())
        self.lon_WMS_eastBound_2.setSizePolicy(sizePolicy)
        self.lon_WMS_eastBound_2.setObjectName(_fromUtf8("lon_WMS_eastBound_2"))
        self.WMS_Bounds_4.addWidget(self.lon_WMS_eastBound_2, 1, 2, 1, 1)
        self.button_req_motu = QtGui.QPushButton(self.tab_Extract_2)
        self.button_req_motu.setEnabled(True)
        self.button_req_motu.setGeometry(QtCore.QRect(220, 390, 136, 32))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_req_motu.sizePolicy().hasHeightForWidth())
        self.button_req_motu.setSizePolicy(sizePolicy)
        self.button_req_motu.setMaximumSize(QtCore.QSize(256, 32))
        self.button_req_motu.setObjectName(_fromUtf8("button_req_motu"))
        self.combo_wms_layer_depth_max_2 = QtGui.QComboBox(self.tab_Extract_2)
        self.combo_wms_layer_depth_max_2.setGeometry(QtCore.QRect(240, 60, 201, 31))
        self.combo_wms_layer_depth_max_2.setObjectName(_fromUtf8("combo_wms_layer_depth_max_2"))
        self.ExtractWidget_2.addTab(self.tab_Extract_2, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.ExtractWidget_2)
        self.gridLayout_7.addLayout(self.verticalLayout_4, 13, 0, 1, 1)
        self.tabWidget_Multi_WMS.addTab(self.tab, _fromUtf8(""))
        self.tab_other_wms = QtGui.QWidget()
        self.tab_other_wms.setObjectName(_fromUtf8("tab_other_wms"))
        self.scrollArea = QtGui.QScrollArea(self.tab_other_wms)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 521, 841))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_7 = QtGui.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 519, 839))
        self.scrollAreaWidgetContents_7.setObjectName(_fromUtf8("scrollAreaWidgetContents_7"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents_7)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents_7)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tree_widget = QtGui.QTreeWidget(self.scrollAreaWidgetContents_7)
        self.tree_widget.setMinimumSize(QtCore.QSize(250, 200))
        self.tree_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tree_widget.setObjectName(_fromUtf8("tree_widget"))
        self.verticalLayout.addWidget(self.tree_widget)
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents_7)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 300))
        self.tabWidget.setMaximumSize(QtCore.QSize(10000, 500))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_WMS = QtGui.QWidget()
        self.tab_WMS.setObjectName(_fromUtf8("tab_WMS"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_WMS)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tab_WMS_layout = QtGui.QVBoxLayout()
        self.tab_WMS_layout.setObjectName(_fromUtf8("tab_WMS_layout"))
        self.combo_wms_layer = QtGui.QComboBox(self.tab_WMS)
        self.combo_wms_layer.setObjectName(_fromUtf8("combo_wms_layer"))
        self.tab_WMS_layout.addWidget(self.combo_wms_layer)
        self.layout_wms_style = QtGui.QHBoxLayout()
        self.layout_wms_style.setObjectName(_fromUtf8("layout_wms_style"))
        self.combo_wms_style_type = QtGui.QComboBox(self.tab_WMS)
        self.combo_wms_style_type.setObjectName(_fromUtf8("combo_wms_style_type"))
        self.layout_wms_style.addWidget(self.combo_wms_style_type)
        self.combo_wms_style_palette = QtGui.QComboBox(self.tab_WMS)
        self.combo_wms_style_palette.setObjectName(_fromUtf8("combo_wms_style_palette"))
        self.layout_wms_style.addWidget(self.combo_wms_style_palette)
        self.tab_WMS_layout.addLayout(self.layout_wms_style)
        self.WMSLabelTimeRange = QtGui.QLabel(self.tab_WMS)
        self.WMSLabelTimeRange.setObjectName(_fromUtf8("WMSLabelTimeRange"))
        self.tab_WMS_layout.addWidget(self.WMSLabelTimeRange)
        self.combo_wms_time = QtGui.QComboBox(self.tab_WMS)
        self.combo_wms_time.setObjectName(_fromUtf8("combo_wms_time"))
        self.tab_WMS_layout.addWidget(self.combo_wms_time)
        self.combo_wms_time_last = QtGui.QComboBox(self.tab_WMS)
        self.combo_wms_time_last.setObjectName(_fromUtf8("combo_wms_time_last"))
        self.tab_WMS_layout.addWidget(self.combo_wms_time_last)
        self.WMSBoundingBoxInfo = QtGui.QLabel(self.tab_WMS)
        self.WMSBoundingBoxInfo.setObjectName(_fromUtf8("WMSBoundingBoxInfo"))
        self.tab_WMS_layout.addWidget(self.WMSBoundingBoxInfo)
        self.WMS_Bounds = QtGui.QGridLayout()
        self.WMS_Bounds.setObjectName(_fromUtf8("WMS_Bounds"))
        self.WMS_northLabel = QtGui.QLabel(self.tab_WMS)
        self.WMS_northLabel.setText(_fromUtf8(""))
        self.WMS_northLabel.setObjectName(_fromUtf8("WMS_northLabel"))
        self.WMS_Bounds.addWidget(self.WMS_northLabel, 1, 1, 1, 1)
        self.WMS_eastBound = QtGui.QLineEdit(self.tab_WMS)
        self.WMS_eastBound.setEnabled(False)
        self.WMS_eastBound.setObjectName(_fromUtf8("WMS_eastBound"))
        self.WMS_Bounds.addWidget(self.WMS_eastBound, 1, 2, 1, 1)
        self.WMS_westBound = QtGui.QLineEdit(self.tab_WMS)
        self.WMS_westBound.setEnabled(False)
        self.WMS_westBound.setObjectName(_fromUtf8("WMS_westBound"))
        self.WMS_Bounds.addWidget(self.WMS_westBound, 1, 0, 1, 1)
        self.WMS_southBound = QtGui.QLineEdit(self.tab_WMS)
        self.WMS_southBound.setEnabled(False)
        self.WMS_southBound.setObjectName(_fromUtf8("WMS_southBound"))
        self.WMS_Bounds.addWidget(self.WMS_southBound, 2, 1, 1, 1)
        self.WMS_northBound = QtGui.QLineEdit(self.tab_WMS)
        self.WMS_northBound.setEnabled(False)
        self.WMS_northBound.setObjectName(_fromUtf8("WMS_northBound"))
        self.WMS_Bounds.addWidget(self.WMS_northBound, 0, 1, 1, 1)
        self.tab_WMS_layout.addLayout(self.WMS_Bounds)
        self.gridLayout_4.addLayout(self.tab_WMS_layout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_WMS, _fromUtf8(""))
        self.tab_WCS = QtGui.QWidget()
        self.tab_WCS.setObjectName(_fromUtf8("tab_WCS"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_WCS)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tab_WCS_layout = QtGui.QVBoxLayout()
        self.tab_WCS_layout.setObjectName(_fromUtf8("tab_WCS_layout"))
        self.combo_wcs_coverage = QtGui.QComboBox(self.tab_WCS)
        self.combo_wcs_coverage.setObjectName(_fromUtf8("combo_wcs_coverage"))
        self.tab_WCS_layout.addWidget(self.combo_wcs_coverage)
        self.WCSLabelTimeRange = QtGui.QLabel(self.tab_WCS)
        self.WCSLabelTimeRange.setMaximumSize(QtCore.QSize(16777215, 25))
        self.WCSLabelTimeRange.setObjectName(_fromUtf8("WCSLabelTimeRange"))
        self.tab_WCS_layout.addWidget(self.WCSLabelTimeRange)
        self.combo_wcs_time = QtGui.QComboBox(self.tab_WCS)
        self.combo_wcs_time.setObjectName(_fromUtf8("combo_wcs_time"))
        self.tab_WCS_layout.addWidget(self.combo_wcs_time)
        self.combo_wcs_time_last = QtGui.QComboBox(self.tab_WCS)
        self.combo_wcs_time_last.setObjectName(_fromUtf8("combo_wcs_time_last"))
        self.tab_WCS_layout.addWidget(self.combo_wcs_time_last)
        self.WCSBoundingBoxInfo = QtGui.QLabel(self.tab_WCS)
        self.WCSBoundingBoxInfo.setObjectName(_fromUtf8("WCSBoundingBoxInfo"))
        self.tab_WCS_layout.addWidget(self.WCSBoundingBoxInfo)
        self.WCS_Bounds = QtGui.QGridLayout()
        self.WCS_Bounds.setObjectName(_fromUtf8("WCS_Bounds"))
        self.WCS_southBound = QtGui.QLineEdit(self.tab_WCS)
        self.WCS_southBound.setObjectName(_fromUtf8("WCS_southBound"))
        self.WCS_Bounds.addWidget(self.WCS_southBound, 2, 1, 1, 1)
        self.WCS_northBound = QtGui.QLineEdit(self.tab_WCS)
        self.WCS_northBound.setObjectName(_fromUtf8("WCS_northBound"))
        self.WCS_Bounds.addWidget(self.WCS_northBound, 0, 1, 1, 1)
        self.WCS_westBound = QtGui.QLineEdit(self.tab_WCS)
        self.WCS_westBound.setObjectName(_fromUtf8("WCS_westBound"))
        self.WCS_Bounds.addWidget(self.WCS_westBound, 1, 0, 1, 1)
        self.WCS_eastBound = QtGui.QLineEdit(self.tab_WCS)
        self.WCS_eastBound.setObjectName(_fromUtf8("WCS_eastBound"))
        self.WCS_Bounds.addWidget(self.WCS_eastBound, 1, 2, 1, 1)
        self.tab_WCS_layout.addLayout(self.WCS_Bounds)
        self.gridLayout_6.addLayout(self.tab_WCS_layout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_WCS, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.button_req_map = QtGui.QPushButton(self.scrollAreaWidgetContents_7)
        self.button_req_map.setMaximumSize(QtCore.QSize(256, 23))
        self.button_req_map.setObjectName(_fromUtf8("button_req_map"))
        self.gridLayout_3.addWidget(self.button_req_map, 8, 0, 1, 1)
        self.button_req_animation = QtGui.QPushButton(self.scrollAreaWidgetContents_7)
        self.button_req_animation.setObjectName(_fromUtf8("button_req_animation"))
        self.gridLayout_3.addWidget(self.button_req_animation, 9, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 3, 0, 1, 1)
        self.combo_dataset_list = QtGui.QComboBox(self.scrollAreaWidgetContents_7)
        self.combo_dataset_list.setObjectName(_fromUtf8("combo_dataset_list"))
        self.gridLayout.addWidget(self.combo_dataset_list, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.buttonManageServers = QtGui.QPushButton(self.scrollAreaWidgetContents_7)
        self.buttonManageServers.setObjectName(_fromUtf8("buttonManageServers"))
        self.horizontalLayout.addWidget(self.buttonManageServers)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_7)
        self.tabWidget_Multi_WMS.addTab(self.tab_other_wms, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget_Multi_WMS)
        THREDDSViewer.setWidget(self.dockWidgetContents)

        self.retranslateUi(THREDDSViewer)
        self.tabWidget_Multi_WMS.setCurrentIndex(0)
        self.ExtractWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(THREDDSViewer)

    def retranslateUi(self, THREDDSViewer):
        THREDDSViewer.setWindowTitle(_translate("THREDDSViewer", "THREDDS Explorer", None))
        self.label_dataset.setText(_translate("THREDDSViewer", "Choose Dataset:", None))
        self.label_variable.setText(_translate("THREDDSViewer", "Choose Variable:", None))
        self.label_area.setText(_translate("THREDDSViewer", "Choose Area:", None))
        self.label_product.setText(_translate("THREDDSViewer", "Choose Product:", None))
        self.label_4.setText(_translate("THREDDSViewer", "Plot parameters :", None))
        self.label_depth.setText(_translate("THREDDSViewer", "Choose Depth:", None))
        self.label_style.setText(_translate("THREDDSViewer", "Choose Style :", None))
        self.WMSLabelTimeRange_2.setText(_translate("THREDDSViewer", "Time range to plot:", None))
        self.combo_wms_time_first_h.setToolTip(_translate("THREDDSViewer", "Last time value to download for this layer\n"
"(If set, will download all the layers between the first and last times)", None))
        self.label_2.setText(_translate("THREDDSViewer", "Bounding Box:", None))
        self.label_Xpixels.setText(_translate("THREDDSViewer", "Xpixels", None))
        self.label_nbcolors.setText(_translate("THREDDSViewer", "Nb colors", None))
        self.label_maxscale.setText(_translate("THREDDSViewer", "Max scale", None))
        self.checkBox_arc.setText(_translate("THREDDSViewer", "Arc", None))
        self.label_minscale.setText(_translate("THREDDSViewer", "Min scale", None))
        self.checkBox_ant.setText(_translate("THREDDSViewer", "Ant", None))
        self.label_Ymedians.setText(_translate("THREDDSViewer", "YMedians", None))
        self.label_Xparallels.setText(_translate("THREDDSViewer", "XParallels", None))
        self.button_req_map_plot.setText(_translate("THREDDSViewer", "Show map in view", None))
        self.button_req_animation_plot.setText(_translate("THREDDSViewer", "Show animation menu >>", None))
        self.ExtractWidget_2.setTabText(self.ExtractWidget_2.indexOf(self.tab_WMS_2), _translate("THREDDSViewer", "WMS", None))
        self.WCSLabelTimeRange_2.setText(_translate("THREDDSViewer", "Time range to download:", None))
        self.combo_wcs_time_2.setToolTip(_translate("THREDDSViewer", "First time value to download for this layer", None))
        self.combo_wcs_time_last_2.setToolTip(_translate("THREDDSViewer", "Last time value to download for this layer\n"
"(If set, will download all the layers between the first and last times)", None))
        self.WCSBoundingBoxInfo_2.setText(_translate("THREDDSViewer", "No bounding box info available", None))
        self.ExtractWidget_2.setTabText(self.ExtractWidget_2.indexOf(self.tab_WCS_2), _translate("THREDDSViewer", "WCS", None))
        self.ExtractWidget_2.setTabText(self.ExtractWidget_2.indexOf(self.tab_WPS_2), _translate("THREDDSViewer", "WPS", None))
        self.label_depth_4.setText(_translate("THREDDSViewer", "Choose min and max Depths:", None))
        self.WMSLabelTimeRange_4.setText(_translate("THREDDSViewer", "Time range to download:", None))
        self.combo_wms_time_first_h_2.setToolTip(_translate("THREDDSViewer", "Last time value to download for this layer\n"
"(If set, will download all the layers between the first and last times)", None))
        self.label_10.setText(_translate("THREDDSViewer", "Bounding Box:", None))
        self.button_req_motu.setText(_translate("THREDDSViewer", "Motu Request", None))
        self.ExtractWidget_2.setTabText(self.ExtractWidget_2.indexOf(self.tab_Extract_2), _translate("THREDDSViewer", "Extraction", None))
        self.tabWidget_Multi_WMS.setTabText(self.tabWidget_Multi_WMS.indexOf(self.tab), _translate("THREDDSViewer", "Cmems", None))
        self.label.setText(_translate("THREDDSViewer", "Choose an available DataSet", None))
        self.tree_widget.headerItem().setText(0, _translate("THREDDSViewer", "SubDatasets and Maps", None))
        self.combo_wms_style_type.setToolTip(_translate("THREDDSViewer", "Style draw type", None))
        self.combo_wms_style_palette.setToolTip(_translate("THREDDSViewer", "Style color palette to use", None))
        self.WMSLabelTimeRange.setText(_translate("THREDDSViewer", "Time range to download:", None))
        self.combo_wms_time.setToolTip(_translate("THREDDSViewer", "First time value to download for this layer", None))
        self.combo_wms_time_last.setToolTip(_translate("THREDDSViewer", "Last time value to download for this layer\n"
"(If set, will download all the layers between the first and last times)", None))
        self.WMSBoundingBoxInfo.setText(_translate("THREDDSViewer", "No bounding box info available", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_WMS), _translate("THREDDSViewer", "WMS", None))
        self.WCSLabelTimeRange.setText(_translate("THREDDSViewer", "Time range to download:", None))
        self.combo_wcs_time.setToolTip(_translate("THREDDSViewer", "First time value to download for this layer", None))
        self.combo_wcs_time_last.setToolTip(_translate("THREDDSViewer", "Last time value to download for this layer\n"
"(If set, will download all the layers between the first and last times)", None))
        self.WCSBoundingBoxInfo.setText(_translate("THREDDSViewer", "No bounding box info available", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_WCS), _translate("THREDDSViewer", "WCS", None))
        self.button_req_map.setText(_translate("THREDDSViewer", "Show map in view", None))
        self.button_req_animation.setText(_translate("THREDDSViewer", "Show animation menu >>", None))
        self.buttonManageServers.setText(_translate("THREDDSViewer", "Manage servers...", None))
        self.tabWidget_Multi_WMS.setTabText(self.tabWidget_Multi_WMS.indexOf(self.tab_other_wms), _translate("THREDDSViewer", "Others", None))

