# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'THREDDS_Explorer_extract_WMS_dockwidget_base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_THREDDSViewer(object):
    def setupUi(self, THREDDSViewer):
        THREDDSViewer.setObjectName(_fromUtf8("THREDDSViewer"))
        THREDDSViewer.resize(541, 831)
        THREDDSViewer.setMinimumSize(QtCore.QSize(154, 118))
        THREDDSViewer.setFloating(True)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setEnabled(True)
        ##sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        ##sizePolicy.setHorizontalStretch(0)
        ##sizePolicy.setVerticalStretch(0)
        ##sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        ##self.scrollArea.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_7 = QtGui.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 521, 786))
        self.scrollAreaWidgetContents_7.setObjectName(_fromUtf8("scrollAreaWidgetContents_7"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents_7)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.combo_dataset_list = QtGui.QComboBox(self.scrollAreaWidgetContents_7)
        self.combo_dataset_list.setObjectName(_fromUtf8("combo_dataset_list"))
        self.gridLayout.addWidget(self.combo_dataset_list, 9, 0, 1, 1)
        self.label_dataset = QtGui.QLabel(self.scrollAreaWidgetContents_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_dataset.sizePolicy().hasHeightForWidth())
        self.label_dataset.setSizePolicy(sizePolicy)
        self.label_dataset.setObjectName(_fromUtf8("label_dataset"))
        self.gridLayout.addWidget(self.label_dataset, 8, 0, 1, 1)
        self.label_product = QtGui.QLabel(self.scrollAreaWidgetContents_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_product.sizePolicy().hasHeightForWidth())
        self.label_product.setSizePolicy(sizePolicy)
        self.label_product.setObjectName(_fromUtf8("label_product"))
        self.gridLayout.addWidget(self.label_product, 6, 0, 1, 1)
        self.combo_product_list = QtGui.QComboBox(self.scrollAreaWidgetContents_7)
        self.combo_product_list.setObjectName(_fromUtf8("combo_product_list"))
        self.gridLayout.addWidget(self.combo_product_list, 7, 0, 1, 1)
        self.label_area = QtGui.QLabel(self.scrollAreaWidgetContents_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_area.sizePolicy().hasHeightForWidth())
        self.label_area.setSizePolicy(sizePolicy)
        self.label_area.setObjectName(_fromUtf8("label_area"))
        self.gridLayout.addWidget(self.label_area, 2, 0, 1, 1)
        self.combo_area_list = QtGui.QComboBox(self.scrollAreaWidgetContents_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_area_list.sizePolicy().hasHeightForWidth())
        self.combo_area_list.setSizePolicy(sizePolicy)
        self.combo_area_list.setObjectName(_fromUtf8("combo_area_list"))
        self.gridLayout.addWidget(self.combo_area_list, 3, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_variable = QtGui.QLabel(self.scrollAreaWidgetContents_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_variable.sizePolicy().hasHeightForWidth())
        self.label_variable.setSizePolicy(sizePolicy)
        self.label_variable.setObjectName(_fromUtf8("label_variable"))
        self.verticalLayout.addWidget(self.label_variable)
        self.combo_variable_list = QtGui.QComboBox(self.scrollAreaWidgetContents_7)
        self.combo_variable_list.setObjectName(_fromUtf8("combo_variable_list"))
        self.verticalLayout.addWidget(self.combo_variable_list)
        self.ExtractWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExtractWidget.sizePolicy().hasHeightForWidth())
        self.ExtractWidget.setSizePolicy(sizePolicy)
        self.ExtractWidget.setMinimumSize(QtCore.QSize(0, 300))
        self.ExtractWidget.setMaximumSize(QtCore.QSize(10000, 500))
        self.ExtractWidget.setObjectName(_fromUtf8("ExtractWidget"))
        self.tab_WMS = QtGui.QWidget()
        self.tab_WMS.setObjectName(_fromUtf8("tab_WMS"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_WMS)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tab_WMS_layout = QtGui.QVBoxLayout()
        self.tab_WMS_layout.setSpacing(0)
        self.tab_WMS_layout.setObjectName(_fromUtf8("tab_WMS_layout"))
        self.label_depth = QtGui.QLabel(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_depth.sizePolicy().hasHeightForWidth())
        self.label_depth.setSizePolicy(sizePolicy)
        self.label_depth.setObjectName(_fromUtf8("label_depth"))
        self.tab_WMS_layout.addWidget(self.label_depth)
        self.combo_wms_layer_depth = QtGui.QComboBox(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_wms_layer_depth.sizePolicy().hasHeightForWidth())
        self.combo_wms_layer_depth.setSizePolicy(sizePolicy)
        self.combo_wms_layer_depth.setObjectName(_fromUtf8("combo_wms_layer_depth"))
        self.tab_WMS_layout.addWidget(self.combo_wms_layer_depth)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.combo_proj = QtGui.QComboBox(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_proj.sizePolicy().hasHeightForWidth())
        self.combo_proj.setSizePolicy(sizePolicy)
        self.combo_proj.setObjectName(_fromUtf8("combo_proj"))
        self.gridLayout_5.addWidget(self.combo_proj, 1, 1, 1, 1)
        self.label_style = QtGui.QLabel(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_style.sizePolicy().hasHeightForWidth())
        self.label_style.setSizePolicy(sizePolicy)
        self.label_style.setObjectName(_fromUtf8("label_style"))
        self.gridLayout_5.addWidget(self.label_style, 0, 0, 1, 1)
        self.combo_colorbar = QtGui.QComboBox(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_colorbar.sizePolicy().hasHeightForWidth())
        self.combo_colorbar.setSizePolicy(sizePolicy)
        self.combo_colorbar.setObjectName(_fromUtf8("combo_colorbar"))
        self.gridLayout_5.addWidget(self.combo_colorbar, 1, 0, 1, 1)
        self.tab_WMS_layout.addLayout(self.gridLayout_5)
        self.WMSLabelTimeRange = QtGui.QLabel(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WMSLabelTimeRange.sizePolicy().hasHeightForWidth())
        self.WMSLabelTimeRange.setSizePolicy(sizePolicy)
        self.WMSLabelTimeRange.setObjectName(_fromUtf8("WMSLabelTimeRange"))
        self.tab_WMS_layout.addWidget(self.WMSLabelTimeRange)
        self.layout_time = QtGui.QGridLayout()
        self.layout_time.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.layout_time.setHorizontalSpacing(6)
        self.layout_time.setVerticalSpacing(2)
        self.layout_time.setObjectName(_fromUtf8("layout_time"))
        self.combo_wms_time_last_d = QtGui.QComboBox(self.tab_WMS)
        self.combo_wms_time_last_d.setObjectName(_fromUtf8("combo_wms_time_last_d"))
        self.layout_time.addWidget(self.combo_wms_time_last_d, 1, 0, 1, 1)
        self.combo_wms_time_last_h = QtGui.QComboBox(self.tab_WMS)
        self.combo_wms_time_last_h.setObjectName(_fromUtf8("combo_wms_time_last_h"))
        self.layout_time.addWidget(self.combo_wms_time_last_h, 1, 1, 1, 1)
        self.combo_wms_time_first_d = QtGui.QComboBox(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_wms_time_first_d.sizePolicy().hasHeightForWidth())
        self.combo_wms_time_first_d.setSizePolicy(sizePolicy)
        self.combo_wms_time_first_d.setObjectName(_fromUtf8("combo_wms_time_first_d"))
        self.layout_time.addWidget(self.combo_wms_time_first_d, 0, 0, 1, 1)
        self.combo_wms_time_first_h = QtGui.QComboBox(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_wms_time_first_h.sizePolicy().hasHeightForWidth())
        self.combo_wms_time_first_h.setSizePolicy(sizePolicy)
        self.combo_wms_time_first_h.setObjectName(_fromUtf8("combo_wms_time_first_h"))
        self.layout_time.addWidget(self.combo_wms_time_first_h, 0, 1, 1, 1)
        self.tab_WMS_layout.addLayout(self.layout_time)
        self.label = QtGui.QLabel(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.tab_WMS_layout.addWidget(self.label)
        self.WMS_Bounds = QtGui.QGridLayout()
        self.WMS_Bounds.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.WMS_Bounds.setHorizontalSpacing(5)
        self.WMS_Bounds.setVerticalSpacing(1)
        self.WMS_Bounds.setObjectName(_fromUtf8("WMS_Bounds"))
        self.WMS_northBound = QtGui.QLineEdit(self.tab_WMS)
        self.WMS_northBound.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WMS_northBound.sizePolicy().hasHeightForWidth())
        self.WMS_northBound.setSizePolicy(sizePolicy)
        self.WMS_northBound.setObjectName(_fromUtf8("WMS_northBound"))
        self.WMS_Bounds.addWidget(self.WMS_northBound, 0, 1, 1, 1)
        self.WMS_southBound = QtGui.QLineEdit(self.tab_WMS)
        self.WMS_southBound.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WMS_southBound.sizePolicy().hasHeightForWidth())
        self.WMS_southBound.setSizePolicy(sizePolicy)
        self.WMS_southBound.setObjectName(_fromUtf8("WMS_southBound"))
        self.WMS_Bounds.addWidget(self.WMS_southBound, 2, 1, 1, 1)
        self.WMS_northLabel = QtGui.QLabel(self.tab_WMS)
        self.WMS_northLabel.setText(_fromUtf8(""))
        self.WMS_northLabel.setObjectName(_fromUtf8("WMS_northLabel"))
        self.WMS_Bounds.addWidget(self.WMS_northLabel, 1, 1, 1, 1)
        self.WMS_eastBound = QtGui.QLineEdit(self.tab_WMS)
        self.WMS_eastBound.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WMS_eastBound.sizePolicy().hasHeightForWidth())
        self.WMS_eastBound.setSizePolicy(sizePolicy)
        self.WMS_eastBound.setObjectName(_fromUtf8("WMS_eastBound"))
        self.WMS_Bounds.addWidget(self.WMS_eastBound, 1, 2, 1, 1)
        self.WMS_westBound = QtGui.QLineEdit(self.tab_WMS)
        self.WMS_westBound.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WMS_westBound.sizePolicy().hasHeightForWidth())
        self.WMS_westBound.setSizePolicy(sizePolicy)
        self.WMS_westBound.setMinimumSize(QtCore.QSize(171, 9))
        self.WMS_westBound.setObjectName(_fromUtf8("WMS_westBound"))
        self.WMS_Bounds.addWidget(self.WMS_westBound, 1, 0, 1, 1)
        self.tab_WMS_layout.addLayout(self.WMS_Bounds)
        self.gridLayout_4.addLayout(self.tab_WMS_layout, 0, 0, 3, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.nbcolors_value = QtGui.QLineEdit(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nbcolors_value.sizePolicy().hasHeightForWidth())
        self.nbcolors_value.setSizePolicy(sizePolicy)
        self.nbcolors_value.setObjectName(_fromUtf8("nbcolors_value"))
        self.gridLayout_3.addWidget(self.nbcolors_value, 10, 3, 1, 1)
        self.label_maxscale = QtGui.QLabel(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_maxscale.sizePolicy().hasHeightForWidth())
        self.label_maxscale.setSizePolicy(sizePolicy)
        self.label_maxscale.setObjectName(_fromUtf8("label_maxscale"))
        self.gridLayout_3.addWidget(self.label_maxscale, 9, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.Ymedians_value = QtGui.QLineEdit(self.tab_WMS)
        self.Ymedians_value.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ymedians_value.sizePolicy().hasHeightForWidth())
        self.Ymedians_value.setSizePolicy(sizePolicy)
        self.Ymedians_value.setMaximumSize(QtCore.QSize(16777215, 16777197))
        self.Ymedians_value.setObjectName(_fromUtf8("Ymedians_value"))
        self.gridLayout_3.addWidget(self.Ymedians_value, 12, 1, 1, 1)
        self.label_minscale = QtGui.QLabel(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_minscale.sizePolicy().hasHeightForWidth())
        self.label_minscale.setSizePolicy(sizePolicy)
        self.label_minscale.setObjectName(_fromUtf8("label_minscale"))
        self.gridLayout_3.addWidget(self.label_minscale, 9, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_Ymedians = QtGui.QLabel(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Ymedians.sizePolicy().hasHeightForWidth())
        self.label_Ymedians.setSizePolicy(sizePolicy)
        self.label_Ymedians.setObjectName(_fromUtf8("label_Ymedians"))
        self.gridLayout_3.addWidget(self.label_Ymedians, 11, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_Xparallels = QtGui.QLabel(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Xparallels.sizePolicy().hasHeightForWidth())
        self.label_Xparallels.setSizePolicy(sizePolicy)
        self.label_Xparallels.setObjectName(_fromUtf8("label_Xparallels"))
        self.gridLayout_3.addWidget(self.label_Xparallels, 11, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.minscale_value = QtGui.QLineEdit(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minscale_value.sizePolicy().hasHeightForWidth())
        self.minscale_value.setSizePolicy(sizePolicy)
        self.minscale_value.setObjectName(_fromUtf8("minscale_value"))
        self.gridLayout_3.addWidget(self.minscale_value, 10, 0, 1, 1)
        self.label_nbcolors = QtGui.QLabel(self.tab_WMS)
        self.label_nbcolors.setObjectName(_fromUtf8("label_nbcolors"))
        self.gridLayout_3.addWidget(self.label_nbcolors, 9, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.Xparallels_value = QtGui.QLineEdit(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Xparallels_value.sizePolicy().hasHeightForWidth())
        self.Xparallels_value.setSizePolicy(sizePolicy)
        self.Xparallels_value.setObjectName(_fromUtf8("Xparallels_value"))
        self.gridLayout_3.addWidget(self.Xparallels_value, 12, 0, 1, 1)
        self.maxscale_value = QtGui.QLineEdit(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxscale_value.sizePolicy().hasHeightForWidth())
        self.maxscale_value.setSizePolicy(sizePolicy)
        self.maxscale_value.setObjectName(_fromUtf8("maxscale_value"))
        self.gridLayout_3.addWidget(self.maxscale_value, 10, 1, 1, 1)
        self.label_Xpixels = QtGui.QLabel(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Xpixels.sizePolicy().hasHeightForWidth())
        self.label_Xpixels.setSizePolicy(sizePolicy)
        self.label_Xpixels.setObjectName(_fromUtf8("label_Xpixels"))
        self.gridLayout_3.addWidget(self.label_Xpixels, 11, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.Xpixels_value = QtGui.QLineEdit(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Xpixels_value.sizePolicy().hasHeightForWidth())
        self.Xpixels_value.setSizePolicy(sizePolicy)
        self.Xpixels_value.setObjectName(_fromUtf8("Xpixels_value"))
        self.gridLayout_3.addWidget(self.Xpixels_value, 12, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 4, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_WMS)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 3, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab_WMS)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.button_req_map = QtGui.QPushButton(self.groupBox)
        self.button_req_map.setEnabled(True)
        self.button_req_map.setGeometry(QtCore.QRect(90, 0, 181, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_req_map.sizePolicy().hasHeightForWidth())
        self.button_req_map.setSizePolicy(sizePolicy)
        self.button_req_map.setMaximumSize(QtCore.QSize(256, 20))
        self.button_req_map.setObjectName(_fromUtf8("button_req_map"))
        self.button_req_animation = QtGui.QPushButton(self.groupBox)
        self.button_req_animation.setGeometry(QtCore.QRect(280, 10, 181, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_req_animation.sizePolicy().hasHeightForWidth())
        self.button_req_animation.setSizePolicy(sizePolicy)
        self.button_req_animation.setMaximumSize(QtCore.QSize(256, 20))
        self.button_req_animation.setIconSize(QtCore.QSize(24, 24))
        self.button_req_animation.setObjectName(_fromUtf8("button_req_animation"))
        self.gridLayout_4.addWidget(self.groupBox, 5, 0, 3, 1)
        self.ExtractWidget.addTab(self.tab_WMS, _fromUtf8(""))
        self.tab_WCS = QtGui.QWidget()
        self.tab_WCS.setObjectName(_fromUtf8("tab_WCS"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_WCS)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tab_WCS_layout = QtGui.QVBoxLayout()
        self.tab_WCS_layout.setObjectName(_fromUtf8("tab_WCS_layout"))
        self.combo_wcs_coverage = QtGui.QComboBox(self.tab_WCS)
        self.combo_wcs_coverage.setObjectName(_fromUtf8("combo_wcs_coverage"))
        self.tab_WCS_layout.addWidget(self.combo_wcs_coverage)
        self.WCSLabelTimeRange = QtGui.QLabel(self.tab_WCS)
        self.WCSLabelTimeRange.setMaximumSize(QtCore.QSize(16777215, 25))
        self.WCSLabelTimeRange.setObjectName(_fromUtf8("WCSLabelTimeRange"))
        self.tab_WCS_layout.addWidget(self.WCSLabelTimeRange)
        self.combo_wcs_time = QtGui.QComboBox(self.tab_WCS)
        self.combo_wcs_time.setObjectName(_fromUtf8("combo_wcs_time"))
        self.tab_WCS_layout.addWidget(self.combo_wcs_time)
        self.combo_wcs_time_last = QtGui.QComboBox(self.tab_WCS)
        self.combo_wcs_time_last.setObjectName(_fromUtf8("combo_wcs_time_last"))
        self.tab_WCS_layout.addWidget(self.combo_wcs_time_last)
        self.WCSBoundingBoxInfo = QtGui.QLabel(self.tab_WCS)
        self.WCSBoundingBoxInfo.setObjectName(_fromUtf8("WCSBoundingBoxInfo"))
        self.tab_WCS_layout.addWidget(self.WCSBoundingBoxInfo)
        self.WCS_Bounds = QtGui.QGridLayout()
        self.WCS_Bounds.setObjectName(_fromUtf8("WCS_Bounds"))
        self.WCS_southBound = QtGui.QLineEdit(self.tab_WCS)
        self.WCS_southBound.setObjectName(_fromUtf8("WCS_southBound"))
        self.WCS_Bounds.addWidget(self.WCS_southBound, 2, 1, 1, 1)
        self.WCS_northBound = QtGui.QLineEdit(self.tab_WCS)
        self.WCS_northBound.setObjectName(_fromUtf8("WCS_northBound"))
        self.WCS_Bounds.addWidget(self.WCS_northBound, 0, 1, 1, 1)
        self.WCS_westBound = QtGui.QLineEdit(self.tab_WCS)
        self.WCS_westBound.setObjectName(_fromUtf8("WCS_westBound"))
        self.WCS_Bounds.addWidget(self.WCS_westBound, 1, 0, 1, 1)
        self.WCS_eastBound = QtGui.QLineEdit(self.tab_WCS)
        self.WCS_eastBound.setObjectName(_fromUtf8("WCS_eastBound"))
        self.WCS_Bounds.addWidget(self.WCS_eastBound, 1, 2, 1, 1)
        self.tab_WCS_layout.addLayout(self.WCS_Bounds)
        self.gridLayout_6.addLayout(self.tab_WCS_layout, 0, 0, 1, 1)
        self.ExtractWidget.addTab(self.tab_WCS, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_depth_2 = QtGui.QLabel(self.tab)
        self.label_depth_2.setGeometry(QtCore.QRect(10, 20, 527, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_depth_2.sizePolicy().hasHeightForWidth())
        self.label_depth_2.setSizePolicy(sizePolicy)
        self.label_depth_2.setObjectName(_fromUtf8("label_depth_2"))
        self.combo_wms_layer_depth_2 = QtGui.QComboBox(self.tab)
        self.combo_wms_layer_depth_2.setGeometry(QtCore.QRect(10, 60, 201, 31))
        self.combo_wms_layer_depth_2.setObjectName(_fromUtf8("combo_wms_layer_depth_2"))
        self.WMSLabelTimeRange_2 = QtGui.QLabel(self.tab)
        self.WMSLabelTimeRange_2.setGeometry(QtCore.QRect(10, 100, 527, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WMSLabelTimeRange_2.sizePolicy().hasHeightForWidth())
        self.WMSLabelTimeRange_2.setSizePolicy(sizePolicy)
        self.WMSLabelTimeRange_2.setObjectName(_fromUtf8("WMSLabelTimeRange_2"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 140, 461, 71))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.layout_time_2 = QtGui.QGridLayout(self.layoutWidget)
        self.layout_time_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.layout_time_2.setSpacing(6)
        self.layout_time_2.setObjectName(_fromUtf8("layout_time_2"))
        self.combo_wms_time_last_d_2 = QtGui.QComboBox(self.layoutWidget)
        self.combo_wms_time_last_d_2.setObjectName(_fromUtf8("combo_wms_time_last_d_2"))
        self.layout_time_2.addWidget(self.combo_wms_time_last_d_2, 1, 0, 1, 1)
        self.combo_wms_time_last_h_2 = QtGui.QComboBox(self.layoutWidget)
        self.combo_wms_time_last_h_2.setObjectName(_fromUtf8("combo_wms_time_last_h_2"))
        self.layout_time_2.addWidget(self.combo_wms_time_last_h_2, 1, 1, 1, 1)
        self.combo_wms_time_first_d_2 = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_wms_time_first_d_2.sizePolicy().hasHeightForWidth())
        self.combo_wms_time_first_d_2.setSizePolicy(sizePolicy)
        self.combo_wms_time_first_d_2.setObjectName(_fromUtf8("combo_wms_time_first_d_2"))
        self.layout_time_2.addWidget(self.combo_wms_time_first_d_2, 0, 0, 1, 1)
        self.combo_wms_time_first_h_2 = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_wms_time_first_h_2.sizePolicy().hasHeightForWidth())
        self.combo_wms_time_first_h_2.setSizePolicy(sizePolicy)
        self.combo_wms_time_first_h_2.setObjectName(_fromUtf8("combo_wms_time_first_h_2"))
        self.layout_time_2.addWidget(self.combo_wms_time_first_h_2, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(10, 220, 527, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.layoutWidget_2 = QtGui.QWidget(self.tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(16, 250, 451, 101))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.WMS_Bounds_2 = QtGui.QGridLayout(self.layoutWidget_2)
        self.WMS_Bounds_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.WMS_Bounds_2.setObjectName(_fromUtf8("WMS_Bounds_2"))
        self.WMS_westBound_2 = QtGui.QLineEdit(self.layoutWidget_2)
        self.WMS_westBound_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WMS_westBound_2.sizePolicy().hasHeightForWidth())
        self.WMS_westBound_2.setSizePolicy(sizePolicy)
        self.WMS_westBound_2.setMinimumSize(QtCore.QSize(171, 9))
        self.WMS_westBound_2.setObjectName(_fromUtf8("WMS_westBound_2"))
        self.WMS_Bounds_2.addWidget(self.WMS_westBound_2, 1, 0, 1, 1)
        self.WMS_northBound_2 = QtGui.QLineEdit(self.layoutWidget_2)
        self.WMS_northBound_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WMS_northBound_2.sizePolicy().hasHeightForWidth())
        self.WMS_northBound_2.setSizePolicy(sizePolicy)
        self.WMS_northBound_2.setObjectName(_fromUtf8("WMS_northBound_2"))
        self.WMS_Bounds_2.addWidget(self.WMS_northBound_2, 0, 1, 1, 1)
        self.WMS_southBound_2 = QtGui.QLineEdit(self.layoutWidget_2)
        self.WMS_southBound_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WMS_southBound_2.sizePolicy().hasHeightForWidth())
        self.WMS_southBound_2.setSizePolicy(sizePolicy)
        self.WMS_southBound_2.setObjectName(_fromUtf8("WMS_southBound_2"))
        self.WMS_Bounds_2.addWidget(self.WMS_southBound_2, 2, 1, 1, 1)
        self.WMS_northLabel_2 = QtGui.QLabel(self.layoutWidget_2)
        self.WMS_northLabel_2.setText(_fromUtf8(""))
        self.WMS_northLabel_2.setObjectName(_fromUtf8("WMS_northLabel_2"))
        self.WMS_Bounds_2.addWidget(self.WMS_northLabel_2, 1, 1, 1, 1)
        self.WMS_eastBound_2 = QtGui.QLineEdit(self.layoutWidget_2)
        self.WMS_eastBound_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WMS_eastBound_2.sizePolicy().hasHeightForWidth())
        self.WMS_eastBound_2.setSizePolicy(sizePolicy)
        self.WMS_eastBound_2.setObjectName(_fromUtf8("WMS_eastBound_2"))
        self.WMS_Bounds_2.addWidget(self.WMS_eastBound_2, 1, 2, 1, 1)
        self.button_req_motu = QtGui.QPushButton(self.tab)
        self.button_req_motu.setEnabled(True)
        self.button_req_motu.setGeometry(QtCore.QRect(170, 380, 136, 32))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_req_motu.sizePolicy().hasHeightForWidth())
        self.button_req_motu.setSizePolicy(sizePolicy)
        self.button_req_motu.setMaximumSize(QtCore.QSize(256, 32))
        self.button_req_motu.setObjectName(_fromUtf8("button_req_motu"))
        self.combo_wms_layer_depth_max_2 = QtGui.QComboBox(self.tab)
        self.combo_wms_layer_depth_max_2.setGeometry(QtCore.QRect(240, 60, 201, 31))
        self.combo_wms_layer_depth_max_2.setObjectName(_fromUtf8("combo_wms_layer_depth_max_2"))
        self.ExtractWidget.addTab(self.tab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.ExtractWidget)
        self.gridLayout.addLayout(self.verticalLayout, 11, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_7)
        self.verticalLayout_2.addWidget(self.scrollArea)
        THREDDSViewer.setWidget(self.dockWidgetContents)

        self.retranslateUi(THREDDSViewer)
        self.ExtractWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(THREDDSViewer)

    def retranslateUi(self, THREDDSViewer):
        THREDDSViewer.setWindowTitle(_translate("THREDDSViewer", "THREDDS Explorer", None))
        self.label_dataset.setText(_translate("THREDDSViewer", "Choose Dataset:", None))
        self.label_product.setText(_translate("THREDDSViewer", "Choose Product:", None))
        self.label_area.setText(_translate("THREDDSViewer", "Choose Area:", None))
        self.label_variable.setText(_translate("THREDDSViewer", "Choose Variable:", None))
        self.label_depth.setText(_translate("THREDDSViewer", "Choose Depth:", None))
        self.label_style.setText(_translate("THREDDSViewer", "Choose Style :", None))
        self.WMSLabelTimeRange.setText(_translate("THREDDSViewer", "Time range to download:", None))
        self.combo_wms_time_first_h.setToolTip(_translate("THREDDSViewer", "Last time value to download for this layer\n"
"(If set, will download all the layers between the first and last times)", None))
        self.label.setText(_translate("THREDDSViewer", "Bounding Box:", None))
        self.label_maxscale.setText(_translate("THREDDSViewer", "Max scale", None))
        self.label_minscale.setText(_translate("THREDDSViewer", "Min scale", None))
        self.label_Ymedians.setText(_translate("THREDDSViewer", "YMedians", None))
        self.label_Xparallels.setText(_translate("THREDDSViewer", "XParallels", None))
        self.label_nbcolors.setText(_translate("THREDDSViewer", "Nb colors", None))
        self.label_Xpixels.setText(_translate("THREDDSViewer", "Xpixels", None))
        self.label_2.setText(_translate("THREDDSViewer", "Plot parameters :", None))
        self.button_req_map.setText(_translate("THREDDSViewer", "Show map in view", None))
        self.button_req_animation.setText(_translate("THREDDSViewer", "Show animation menu >>", None))
        self.ExtractWidget.setTabText(self.ExtractWidget.indexOf(self.tab_WMS), _translate("THREDDSViewer", "WMS", None))
        self.WCSLabelTimeRange.setText(_translate("THREDDSViewer", "Time range to download:", None))
        self.combo_wcs_time.setToolTip(_translate("THREDDSViewer", "First time value to download for this layer", None))
        self.combo_wcs_time_last.setToolTip(_translate("THREDDSViewer", "Last time value to download for this layer\n"
"(If set, will download all the layers between the first and last times)", None))
        self.WCSBoundingBoxInfo.setText(_translate("THREDDSViewer", "No bounding box info available", None))
        self.ExtractWidget.setTabText(self.ExtractWidget.indexOf(self.tab_WCS), _translate("THREDDSViewer", "WCS", None))
        self.label_depth_2.setText(_translate("THREDDSViewer", "Choose min and max Depths:", None))
        self.WMSLabelTimeRange_2.setText(_translate("THREDDSViewer", "Time range to download:", None))
        self.combo_wms_time_first_h_2.setToolTip(_translate("THREDDSViewer", "Last time value to download for this layer\n"
"(If set, will download all the layers between the first and last times)", None))
        self.label_9.setText(_translate("THREDDSViewer", "Bounding Box:", None))
        self.button_req_motu.setText(_translate("THREDDSViewer", "Motu Request", None))
        self.ExtractWidget.setTabText(self.ExtractWidget.indexOf(self.tab), _translate("THREDDSViewer", "Extraction", None))

